# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: voting.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvoting.proto\x12\x06voting\"`\n\rVotingRequest\x12\x0b\n\x03url\x18\x01 \x01(\t\x12(\n\x04vote\x18\x02 \x01(\x0e\x32\x1a.voting.VotingRequest.Vote\"\x18\n\x04Vote\x12\x06\n\x02UP\x10\x00\x12\x08\n\x04\x44OWN\x10\x01\"&\n\x0eVotingResponse\x12\x14\n\x0c\x63onfirmation\x18\x01 \x01(\t2?\n\x06Voting\x12\x35\n\x04Vote\x12\x15.voting.VotingRequest\x1a\x16.voting.VotingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'voting_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_VOTINGREQUEST']._serialized_start=24
  _globals['_VOTINGREQUEST']._serialized_end=120
  _globals['_VOTINGREQUEST_VOTE']._serialized_start=96
  _globals['_VOTINGREQUEST_VOTE']._serialized_end=120
  _globals['_VOTINGRESPONSE']._serialized_start=122
  _globals['_VOTINGRESPONSE']._serialized_end=160
  _globals['_VOTING']._serialized_start=162
  _globals['_VOTING']._serialized_end=225
# @@protoc_insertion_point(module_scope)
